### ISSUE TITLE
Empty buttons

### ISSUE THREAD

**Issue by Chungalin** [jasp00/signTextJS#5]
Firefox 40.0.3 32bit WinXP SP3. signTextJS plus 0.8.6.
When trying to sign, OK and Cancel buttons appear empty, about a few pixels tall. It happenes when requesting a digital certificate from Spain’s Royal Mint (FNMT). I managed to guess which one was the OK button and signing was successful, but this should be addressed. Website error or addon error? Who determines buttons text?

![signtextjs issue](https://cloud.githubusercontent.com/assets/22280228/24580266/6835fdc8-1705-11e7-951d-d25bdae5792a.png)

**Comment by jasp00** [comment]
>Firefox 40.0.3 32bit WinXP SP3.

Because of security reasons, it is recommended that you upgrade to the latest Firefox ESR, which still [supports](https://www.mozilla.org/en-US/firefox/45.0esr/system-requirements/) Windows XP.

>Website error or addon error?

This is an add-on issue. Unfortunately, next version of signTextJS plus is expected to be a WebExtension, so backward compatibility may be dropped. However, you may fix the error in that event.

>Who determines buttons text?

The interface is at [`data/certChooser.html`](https://github.com/jasp00/signTextJS/blob/master/data/certChooser.html). My guess is that Firefox 40 does not support the `data-l10n-id` attribute.

If you want to fix this yourself, you may ask for advice.

**Comment by jasp00** [comment]
Version 0.9.0 is a WebExtension and Firefox 40 is not supported.
